trigger:
  batch: true

name: $(BuildID)

variables:
  - group: keyvault-image-build-variables
  - group: packer-image-build-variables
  
stages:
- stage: WS_2019_datacenter
  displayName: Windows Server 2019 Azure Edition
  jobs:
  - job: build
    displayName: Build Image
    pool:
      name: frsteam_agent
      demands:
        - agent.name -equals agent 
    steps:
    - task: riezebosch.Packer.PackerTool.PackerTool@0
      displayName: 'Use Packer 1.7.8'
      inputs: 
        version: 1.7.8
    - task: PackerBuild@1
      displayName: 'Build Image'
      inputs:
          templateType: custom
          customTemplateLocation: 'packer.json'
          customTemplateParameters: '{"ADOServicePrincipalAppId":"$(ADOAppID)","ADOServicePrincipalSecret":"$(ADOAppSecret)","TenantId":"$(TenantId)","SubscriptionId":"$(SubscriptionId)","ImageDestRG":"$(ImageDestRG)","TempResourceGroup":"$(TempResourceGroup)","VirtualNetwork":"$(VirtualNetwork)","VirtualNetworkRG":"$(VirtualNetworkRG)","Subnet":"$(Subnet)","Location":"$(Location)","VMSize":"$(VMSize)","StorageAccountInstallersName":"$(StorageAccountName)","StorageAccountInstallersKey":"$(StorageAccountKey)","StorageAccountInstallersPath":"$(filesharePath)"}'
          imageUri: BuildImage
    - task: nkdagility.variablehydration.variabledehydration-task.variabledehydration@0
      displayName: 'Save Build Variables: BuildImage'
      inputs:
        prefixes: BuildImage
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: |
          packer.json
          azure-pipelines.yml
          !.git/**/*
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: yml & json'
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: MyBuildOutputs
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)' 
        #includeRootFolder: true 
        archiveType: 'zip' # Options: zip, 7z, tar, wim
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 
        replaceExistingArchive: true 
        verbose: true
    #- task: PublishBuildArtifacts@1
    #  displayName: 'Publish Artifact: Build Image and associated Template'
    #  inputs:
    #    ArtifactName: 'Build Image'
    #    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    #    publishLocation: 'Container'
